# Dimensiones, tensores y reshape

<img src="src/img/dimensiones.png">

Tensor 

<img src="src/img/tensor.png">

In [1]:
import numpy as np

## Scalar

In [6]:
sc = np.array(42)
print("shape: ", sc.shape)
sc.ndim

shape:  ()


0

## Vector

In [7]:
sc = np.array([42,43,2,54,6,23])
print("shape: ", sc.shape)
print("dimen: ", sc.ndim)

shape:  (6,)


1

## Matrix

In [8]:
sc = np.array([[42,43,2,54,6,23], [59,5,3,45,21,4]])
print("shape: ", sc.shape)
print("dimen: ", sc.ndim)

shape:  (2, 6)
dimen:  2


## Tensor

In [10]:
sc = np.array([[[42,43,2,54,6,23], [59,5,3,45,21,4]], 
               [[42,43,2,54,6,23], [59,5,3,45,21,4]],
               [[42,43,2,54,6,23], [59,5,3,45,21,4]]])
print("shape: ", sc.shape)
print("dimen: ", sc.ndim)

shape:  (3, 2, 6)
dimen:  3


# Reshape

In [16]:
rs = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
print(rs.shape)
rs = rs.reshape(10,1)
print(rs)
print(rs.shape)
rs = rs.reshape(2,5)
print(rs)
print(rs.shape)

(5, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


# Transpose

In [23]:
print(rs.shape)
print(rs)
# tr = np.transpose(rs)
tr = rs.T
print('\n',tr.shape)
print(tr)


(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]

 (5, 2)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
